import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "react-native-size-matters";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#D5F8D1",
  },
  section: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-start",
    backgroundColor: "#F5F5F5",
    paddingTop: verticalScale(57),
    paddingBottom: verticalScale(10),
    paddingLeft: scale(24),
    paddingRight: scale(24),
    borderBottomColor: "#4B4B4B",
    borderBottomWidth: moderateScale(2),
  },
  inputTitle: {
    paddingLeft: scale(8),
    paddingBottom: verticalScale(4),
    color: "#636363",
    fontSize: moderateScale(10),
    fontFamily: "Pretendard_Regular",
  },
  text: {
    flex: 1,
    textAlign: "center",
    alignSelf: "center",
    right: scale(10),
    color: "#1B1B1B",
    fontSize: moderateScale(16),
    fontFamily: "Pretendard_SemiBold",
  },
  textInput: {
    backgroundColor: "#fff",
    paddingLeft: scale(12),
    paddingRight: scale(12),
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(8),
    borderBottomColor: "#B9B9B9",
    borderBottomWidth: moderateScale(2),
    height: verticalScale(40),
    fontSize: moderateScale(28),
  },
  textCount: {
    textAlign: "right",
    color: "#636363",
    fontSize: moderateScale(12),
    fontFamily: "Pretendard_Regular",
    paddingRight: scale(8),
    paddingTop: verticalScale(2),
  },
  topText: {
    color: "#1B1B1B",
    fontSize: moderateScale(16),
    fontFamily: "Pretendard_Regular",
  },
  topSubText: {
    fontSize: moderateScale(16),
    fontFamily: "Pretendard_SemiBold",
  },
  icon: {
    height: moderateScale(24),
    width: moderateScale(24),
    alignSelf: "center",
  },
  plusButtonContainer: {
    marginTop: verticalScale(8),
    marginBottom: verticalScale(32),
    alignItems: "center",
  },
  line: {
    height: verticalScale(2),
    width: "100%",
    backgroundColor: "#4B4B4B",
  },
  timeContainer: {
    paddingRight: scale(8),
    paddingLeft: scale(8),
    flexDirection: "column",
    gap: scale(8),
    marginTop: verticalScale(8),
  },
  timeSection: { flexDirection: "row", justifyContent: "space-between" },
  bottomText: {
    color: "#1B1B1B",
    fontSize: moderateScale(20),
    fontFamily: "Pretendard_Regular",
  },
  bottomSubText: {
    fontSize: moderateScale(20),
    fontFamily: "Pretendard_Regular",
  },
  middleSection: {
    paddingRight: scale(24),
    paddingLeft: scale(24),
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(16),
  },
  noticeText: {
    padding: scale(8),
    color: "#636363",
    fontSize: moderateScale(10),
    fontFamily: "Pretendard_Medium",
    textAlign: "center",
  },
  bottomSection: {
    paddingRight: scale(8),
    paddingLeft: scale(8),
    gap: scale(8),
    marginBottom: verticalScale(24),
  },
  bottomBox: {
    justifyContent: "flex-end",
    gap: scale(8),
    flexDirection: "row",
  },
  buttonTopText: {
    fontSize: moderateScale(12),
    fontFamily: "Pretendard_Regular",
    color: "#B9B9B9",
    textAlign: "center",
  },
});
